config/routes.rb
Rails.application.routes.draw do
  resources :infos
  root 'infos#index'

end

app/models/info.rb
class Info < ActiveRecord::Base

	def self.to_csv(options = {})
		CSV.generate(options) do |csv|
			csv << column_names
			all.each do |info|
				csv << info.attributes.values_at(*column_names)
			end
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
  before_action :set_info, only: [:show, :edit, :update, :destroy]
  respond_to :html, :csv, :xls, :json

  # GET /infos
  # GET /infos.json
  def index
    @locations = ["Yale","Wellesley","Wheaton","Norwood"]
    @infos = params[:location].blank? ? Info.all : Info.where(:location => params[:location])
    respond_to do |format|
      format.html
      format.csv { send_data @infos.to_csv, :filename => 'infos.csv' }
      format.xls { send_data @infos.to_csv(col_sep: "\t"), :filename => 'infos.xls'}
    end
  end

  # GET /infos/1
  # GET /infos/1.json
  def show
  end

  # GET /infos/new
  def new
    @info = Info.new
  end

  # GET /infos/1/edit
  def edit
  end

  # POST /infos
  # POST /infos.json
  def create
    @info = Info.new(info_params)

    respond_to do |format|
      if @info.save
        format.html { redirect_to @info, notice: 'Info was successfully created.' }
        format.json { render :show, status: :created, location: @info }
      else
        format.html { render :new }
        format.json { render json: @info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /infos/1
  # PATCH/PUT /infos/1.json
  def update
    respond_to do |format|
      if @info.update(info_params)
        format.html { redirect_to @info, notice: 'Info was successfully updated.' }
        format.json { render :show, status: :ok, location: @info }
      else
        format.html { render :edit }
        format.json { render json: @info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /infos/1
  # DELETE /infos/1.json
  def destroy
    @info.destroy
    respond_to do |format|
      format.html { redirect_to infos_url, notice: 'Info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_info
      @info = Info.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def info_params
      params.require(:info).permit(:name, :location, :note, :macs, :mactype)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/views/infos/_form.html.erb
<%= form_for(@info) do |f| %>
  <% if @info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@info.errors.count, "error") %> prohibited this info from being saved:</h2>

      <ul>
      <% @info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :note %><br>
    <%= f.text_field :note %>
  </div>
  <div class="field">
    <%= f.label :macs %><br>
    <%= f.text_field :macs %>
  </div>
  <div class="field">
    <%= f.label :mactype %><br>
    <%= f.text_field :mactype %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/infos/edit.html.erb
<h1>Editing Info</h1>

<%= render 'form' %>

<%= link_to 'Show', @info %> |
<%= link_to 'Back', infos_path %>

app/views/infos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Device Info</h1>
<form>
  <%= select_tag "location", options_for_select(@locations), prompt: "Select a location", include_blank: "All", :onchange => "this.form.submit();"%>
</form>
<p>
  Download:
  <%= link_to "CSV", infos_path(request.parameters.merge({:format => :csv})) %> |
  <%= link_to "Excel", infos_path(request.parameters.merge({:format => :xls})) %>
</p>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Note</th>
      <th>Macs</th>
      <th>MacType</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @infos.each do |info| %>
      <tr>
        <td><%= info.name %></td>
        <td><%= info.location %></td>
        <td><%= info.note %></td>
        <td><%= info.macs %></td>
        <td><%= info.mactype %></td>
        <td><%= link_to 'Show', info %></td>
        <td><%= link_to 'Edit', edit_info_path(info) %></td>
        <td><%= link_to 'Destroy', info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add a device info', new_info_path %>

app/views/infos/index.xls.erb
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Note</th>
      <th>Macs</th>
      <th>MacType</th>
    </tr>
  </thead>

  <tbody>
    <% @infos.each do |info| %>
      <tr>
        <td><%= info.name %></td>
        <td><%= info.location %></td>
        <td><%= info.note %></td>
        <td><%= info.macs %></td>
        <td><%= info.mactype %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/infos/new.html.erb
<h1>New Info</h1>

<%= render 'form' %>

<%= link_to 'Back', infos_path %>

app/views/infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @info.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @info.location %>
</p>

<p>
  <strong>Note:</strong>
  <%= @info.note %>
</p>

<p>
  <strong>Macs:</strong>
  <%= @info.macs %>
</p>

<p>
  <strong>MacType:</strong>
  <%= @info.mactype %>
</p>

<%= link_to 'Edit', edit_info_path(@info) %> |
<%= link_to 'Back', infos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DeviceInfo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>